export const testDialogs = [
	[
		{message: 'dialogs one message one', time: 'сейчас', read: false},
		{message: 'dialogs one message two', time: 'сейчас', read: false},
		{message: 'dialogs one message three', time: 'сейчас', read: false},
		{message: 'Я ща стрепсилс тебе куплю, п…', time: 'сейчас', read: false},
	],
	[
		{message: 'dialogs two message one', time: '13:01', read: true},
		{message: 'dialogs two message two', time: '13:01', read: false},
		{message: 'dialogs two message three', time: '13:01', read: true},
		{message: 'Го в WhatsApp, я создал', time: '13:01', read: false},
	],
	[
		{message: 'dialogs three message one', time: '11:59', read: false},
		{message: 'dialogs three message two', time: '11:59', read: false},
		{message: 'dialogs three message three', time: '11:59', read: true},
		{message: 'Мы все свидетельствуем …', time: '11:59', read: false},
	],
	[
		{message: 'dialogs four message one', time: 'Вчера', read: true},
		{message: 'dialogs four message two', time: 'Вчера', read: false},
		{message: 'dialogs four message three', time: 'Вчера', read: true},
		{message: 'Кек! Ты то меня никогда не пре…', time: 'Вчера', read: true},
	],
	[
		{message: 'dialogs five message one', time: '09:33', read: false},
		{message: 'dialogs five message two', time: '09:33', read: false},
		{message: 'dialogs five message three', time: '09:33', read: false},
		{message: 'Привет! Я ща в аптеку заско…', time: '09:33', read: false},
	],
];

export const testContacts = [
	{
		avatar: '',
		isOnline: false,
		id: '43-20-123',
		name: 'Jack the Ripper',
		dialogs: testDialogs[0],
	},
	{
		avatar: '',
		isOnline: true,
		id: '43-21-123',
		name: 'Ян Борисович Кум',
		dialogs: testDialogs[1],
	},
	{
		avatar: '',
		isOnline: false,
		id: '43-22-123',
		name: 'Фёдор Достоевский',
		dialogs: testDialogs[2],
	},
	{
		avatar: '',
		isOnline: true,
		id: '43-23-123',
		name: 'Гай Юлий Цезарь',
		dialogs: testDialogs[3],
	},
	{
		avatar: '',
		isOnline: false,
		id: '43-24-123',
		name: 'Алан Тьюринг',
		dialogs: testDialogs[4],
	},
	{
		avatar: '',
		isOnline: false,
		id: '43-25-123',
		name: 'Александр Блок',
		dialogs: testDialogs[0],
	},
	{
		avatar: '',
		isOnline: false,
		id: '43-26-123',
		name: '123',
		dialogs: testDialogs[2],
	},
	{
		avatar: '',
		isOnline: false,
		id: '44-27-123',
		name: '123456',
		dialogs: testDialogs[1],
	},
	{
		avatar: '',
		isOnline: false,
		id: '45-28-123',
		name: 'name',
		dialogs: testDialogs[3],
	},
	{
		avatar: '',
		isOnline: false,
		id: '46-29-123',
		name: 'test name',
		dialogs: testDialogs[4],
	},
	{
		avatar: '',
		isOnline: false,
		id: '47-29-123',
		name: 'test name',
		dialogs: testDialogs[4],
	},
	{
		avatar: '',
		isOnline: false,
		id: '48-29-123',
		name: 'test name',
		dialogs: testDialogs[4],
	},
	{
		avatar: '',
		isOnline: false,
		id: '49-29-123',
		name: 'test name',
		dialogs: testDialogs[4],
	},
];
